apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-app
  labels:
    app: dvwa-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dvwa-app
  template:
    metadata:
      labels:
        app: dvwa-app
    spec:
      containers:
        - name: dvwa-app
          image: us-central1-docker.pkg.dev/PROJECT_ID/artifact-repo/dvwa-app:latest
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "dvwa"
            - name: MYSQL_HOST
              value: "mysql"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
spec:
  type: LoadBalancer
  selector:
    app: dvwa-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
